apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 67d9f5b752e297077b8f63f0c2d3f62aaeb65a01

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: 849d383e8375da1edc138f9f9b170fcaa61c7933

namespace: konflux-ui
