apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dex
  - proxy
  - route-and-oauth.yaml
  - ../../base

images:
  - name: quay.io/konflux-ci/konflux-ui
    newTag: 7723e1f6b044c72a88cd257fa5949146cd0ad9cd

  - name: quay.io/konflux-ci/oauth2-proxy
    newTag: d86532e15ecd67a9c23586c546a7838495683622

namespace: konflux-ui
